server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/demo_spring
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pvi@2019
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      show_sql: true


