language: java
jdk:
  - openjdk14
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      - secure: lW0UeF5Vw7Xz4MD/0NMZ8SAMmQk2Kt+ZVsSvnTBnDnVFPksWOc36NOgdvGWzJy5+GS9tjPXnQLYRhuUSv/Q1jbzA95V7L0EJ854WjFFAh4fyzyJEgkJjKPRD1XcaQFmslIVkPyHWP4UTVOkmtWcAS4BsMIoLF5uUE1D0WgmmqmBvbNQzGqW9dCz6hQdvRT/fdgdNSCHfstYdrPDKT70/a8UQtHT1mFU8BAm7luesL331OMGzINs6w4hgLDI1nwCCpzbPEKXq1dq+vQq93OI1h0Rx8YuJO0cnRGvwV41YshacCsqta4HzfzVT8KzRtvuqcRZhxFpaHtcsI4kf45iAIiFEtdeiRcv8EQXeWT4ER5C8x68XgoMnXuQFqy9cducWbo29UO+Ox+cZftbgfWYEsalwlNMLPaDP1uNbyVi15iSpnr5ZcXDUfd0Mya4l5pR5ayiLzhA+l51sK5uT3ZVICQTFj9Ye2YXX+y3+SOOYcwEbsHU52ctHjxqM6HRR7lRyOz4M+mfoP46a/w/LOjAdSj2uralK5ze1Ik0ZH4qhad0mG/K98pIKnOKlfwms/9kY1nDpxZdZsR+uEoPV01MwQ0VNiKqJwkpzjy7ncHquM/EJ8HrijpzInNTRI4Tg2UKQYQLRf4bJyzriePjeugG0KUiMVW5fD65juJsIySzeM0s=
